# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: yarn install
    - run: yarn test

  build-and-publish:
    runs-on: ubuntu-latest

    needs: [ test ]

    strategy:
      matrix:
        package: [testing-utils]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: yarn install
      working-directory: packages/${{ matrix.package }}
    - run: yarn build
      working-directory: packages/${{ matrix.package }}

    # Ideally all of the following code is handled by a GitHub actions, but
    # unfortunately it doesn't support subdirectories yet:
    # https://github.com/JS-DevTools/npm-publish/issues/34
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
    - name: Get current version in registry
      uses: martinbeentjes/npm-get-version-action@v1.1.0
      id: registry-version
      with:
        path: packages/${{ matrix.package }}/
    - name: Get current version in package.json
      uses: nyaa8/package-version@v1
      with:
        path: packages/${{ matrix.package }}/package.json
    # This logic can and probably should be improved, but for now it's fine.
    - name: Publish new version if versions differ
      if: ${{ matrix.package != env.PACKAGE_VERSION }}
      run: yarn publish --access restriced
      working-directory: packages/${{ matrix.package }}