# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: yarn install
    - run: yarn test

  build-and-publish:
    runs-on: ubuntu-latest

    needs: [ test ]

    strategy:
      matrix:
        package: [testing-utils]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: yarn install
      working-directory: packages/${{ matrix.package }}
    - run: yarn build
      working-directory: packages/${{ matrix.package }}

    - uses: JS-DevTools/npm-publish@v1
      with:
        package: packages/${{ matrix.package }}/package.json
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: https://npm.pkg.github.com/
        access: restricted
        check-version: true
